### ISSUE TITLE
HockeyApp and ApplicationInsights

### ISSUE THREAD

**Issue by catlan** [Microsoft/ApplicationInsights-OSX#17]
Class BITCrashCXXExceptionWrapperException is implemented in both .app/Contents/Frameworks/HockeySDK.framework/Versions/A/HockeySDK and .app/Contents/Frameworks/ApplicationInsightsOSX.framework/Versions/A/ApplicationInsightsOSX. One of the two will be used. Which one is undefined.

See https://github.com/Microsoft/ApplicationInsights-OSX/blob/74a4cb5911b2b3c939e1415a849cbcd5b78ae4dd/Classes/MSAICrashManager.m#L71

**Comment by ghost** [comment]
Thanks. This has already been fixed in the develop branch, see here: https://github.com/Microsoft/ApplicationInsights-OSX/commit/ad8b4cf1fcf8c780c1eac330b4a71a9bbbf9befa
