### ISSUE TITLE
Note that code-signing is recommended 

### ISSUE THREAD

**Issue by catlan** [Microsoft/ApplicationInsights-OSX#18]
I would note in the read-me that code-signing results in a better user experience for non-MAS apps. 

Without it after an update the Keychain will prompt the user asking if the app is allowed to access bundleIdentify.MSAI keychain entry.

**Comment by ghost** [comment]
Thanks, we just added this, see here: https://github.com/Microsoft/ApplicationInsights-OSX/commit/54ec7904e4503e497ba08fd9c655e66d7cef16e4

Code-Signing should be default since a while, as the default OS X setting is not to allow apps to be started that are not code-signed (GateKeeper).
