### ISSUE TITLE
No data reported to backend any more

### ISSUE THREAD

**Issue by ChristianPraherKoeppl** [Microsoft/ApplicationInsights-OSX#24]
Hello everyone,

for some days now (at most 2 weeks) no OS X client data is reported to the Azure backend anymore.
There is no obvious bug with the client API because the API reports that the data was sent successfully, e.g.:
`[MSAI] -[MSAIApplicationInsights start]/110 INFO: Starting MSAIManager`
`[MSAI]_ -[MSAIApplicationInsights start]/132 INFO: Starting MSAITelemetryManage`
`[MSAI] __80-[MSAIPersistence persistBundle:ofType:enableNotifications:withCompletionBlock:]_block_invoke/69 Wrote /var/root/Library/Application Support/com.microsoft.ApplicationInsights/regularPrio/app-insights-bundle-2561752B-624C-4AFF-AFF2-17A8D452CA27`
`[MSAI] __31-[MSAISender sendRequest:path:]_block_invoke/103 Sent data with status code: 200`
`[MSAI] __31-[MSAISender sendRequest:path:]_block_invoke/104 Response data:`
`[MSAI] __36-[MSAIPersistence deleteFileAtPath:]_block_invoke/186 Successfully deleted file at path /private/var/root/Library/Application Support/com.microsoft.ApplicationInsights/regularPrio/app-insights-bundle-2561752B-624C-4AFF-AFF2-17A8D452CA27`

The backend URL is https://dc.services.visualstudio.com/v2/track and resolves to 40.114.241.141 in our region (central Europe).
Also Wireshark shows that items are being sent to 40.114.241.141 on port 443.
We are also sending telemetry data from Windows clients which post the data to the same backend URL and for Windows the sending of the data works.

So this seems super strange to us. Might it be that the data is filtered out on the backend because of the deprecation of the API? Do we need to switch to HockeySDK to get it working again?

Thanks for any answers or hints as to what we can do about this issue!

Christian Praher-Köppl

**Comment by lumaxis** [comment]
Hey @ChristianPraherKoeppl, what kinds of telemetry data is it that you're trying to send? Events, Metrics, Pageviews, … ?

**Comment by lumaxis** [comment]
Also: Could you maybe provide a sample payload of the data you're trying to send? That would allow us to better investigate what exactly is going wrong. If you feel uncomfortable posting the payload on a public Github issue, feel free to open a private ticket here: http://support.hockeyapp.net/dashboard

**Comment by ChristianPraherKoeppl** [comment]
It is both metrics and properties. If we do not have numeric data we omit the metrics and if we do not have string data we omit the properties.
Please see the attached file as
[app-insights-bundle-3C8A0F88-0983-40A6-8876-A81A07C0608E.txt](https://github.com/Microsoft/ApplicationInsights-OSX/files/132972/app-insights-bundle-3C8A0F88-0983-40A6-8876-A81A07C0608E.txt)

 an example of a payload I grabbed from /var/root/Library/Application Support/com.microsoft.ApplicationInsights/regularPrio. It has the name app-insights-bundle-3C8A0F88-0983-40A6-8876-A81A07C0608E. I disconnected my network connection so I could grab it out but as soon as I re-connect it is seemingly sent OK (200 HTTP).

Please note that I have removed the instrumentation key "ikey" value for the purpose of the upload, but it is there and it is correct.

**Comment by ChristianPraherKoeppl** [comment]
Hi everyone,
any update on this issue already? We're still not seeing data in the https://portal.azure.com backend.
We're trying to upgrade to the latest version (1.0-beta.2) now but honestly I would be quite upset if the library would change so radical between two minor versions that no data is being processed by the backend anymore.s

**Comment by sejjiin** [comment]
Not sure if it's related, but we encountered something similar where data suddenly just stopped showing up (without us changing anything client-side). Turns out it was because we were using
`NSNumber numberWithBool:` to send in some metrics. We had to change to `NSNumber numberWithDouble:` and the data started going through again.

**Comment by lumaxis** [comment]
So sorry @ChristianPraherKoeppl! I've been at MWC in Spain the last couple of days so digging into this got delayed a bit. I'm going to bug my colleagues in the data pipeline team again and see that we finally get this figured out. Thanks for your patience!

**Comment by ChristianPraherKoeppl** [comment]
Hi there, 
any news regarding the issue of the data not being processed by the Azure backend anymore?
We have meanwhile upgraded to the latest SDK 1.0-beta.2 but to no avail unfortunately.
What else could we do or into which direction should we investigate in order to get this done?
Should I send you a more thorough dump of the data that is being sent by us?
Really looking forward to a solution of this problem as we are very close to releasing our product and we'd love to see telemetry data working.

Thanks,

Christian

**Comment by lumaxis** [comment]
Hey Christian,
sorry again, this took a bit longer to figure out. At the end, the problem is very simple:
Somewhere in your code you are setting `user.accountAcquisitionDate = @"-"`. As this is obviously not a valid date, this causes your data to be silently dropped somewhere deeper in our data processing pipeline.
Removing this setting should fix your problem and allow the data to show up again.

**Comment by ChristianPraherKoeppl** [comment]
Hi Lukas,

THANKS BIG TIME, you really saved our day -- Removing the property really did the trick and telemetry data is now coming through again :+1: 

Just two things:
- Do we need to be afraid that the backend validation will be more rigid again any time soon and will hence reject data that was previously accepted (like it was the case with our data, as I said it used to work before with the accountAquisitionDate being set to "-"). E.g. I have now also omitted sending a userAgent string. -- Could this be a reason in the future as to why the telemetry event is rejected by the backend (because it is not present)?
- Just a minor thing: Concerning the API I think it would be great if the accountAcquisitionDate was defined as NSDate instead of NSString as that would remove the possibility of supplying invalid data like a "-". Or is there a reason why it is a string?

But thanks again for your quick response and the effort you put into solving our issue :-)

**Comment by lumaxis** [comment]
Glad I could help 😊
To answer your questions:
- I think we will be adding more validations for cases like yours. We don't want to have payloads quietly disappear in a black hole but rather return helpful errors if the data is factually unusable. This is right now only an idea and I will investigate our options for this in the next couple of days by also talking to some other colleagues who are working closer to the actual data processing pipeline.
- Yea, in hindsight this definitely does not seem ideal but is a relic of when the whole user context API was still private and we missed updating it properly. Unfortunately, we don't have any future releases planned for this SDK and won't invest more development time into it. If you want, we would likely be happy to accept a Pull Request that deprecates the current API and replaces it with a working `NSDate` equivalent. This could then be included in case we need to do an urgent bugfix release or just be helpful for other people directly using the source in this repo.
