### ISSUE TITLE
MSAIUser properties are persisted even if no more being set

### ISSUE THREAD

**Issue by ChristianPraherKoeppl** [Microsoft/ApplicationInsights-OSX#25]
Hi everyone,
please note that this directly relates to issue [No data reported to backend any more](https://github.com/Microsoft/ApplicationInsights-OSX/issues/24).

As Lukas thankfully pointed out we have wrongly set the property accountAcquisitionDate of class MSAIUser to "-" which caused or telemetry JSON events not to be processed by the MS Azure backend anymore. 
Following Lukas' advice we have now simply omitted setting the accountAcquisitionDate property. 
Now this worked fine for those tests were we have not previously installed a version of our product before.
But on machines were a previous version of our product was installed this does not work. The reason is that the MSAIUser context seemingly is serialized on disk (For our product in "/var/root/Library/Preferences/sgd.plist").
Then the MSAIUser class is loaded from this serialization in its "setUserWithConfigurationBlock:" which in turn loads the serialization from disk with the "loadUser" message.
Now what we had to do is to explicitly set the accountAcquisitionDate to nil to get rid of the previous configuration. In addition a restart was required to really have the new accountAcquisitionDate property value set.
Since the API is deprecated already I guess that this serialization behavior wont be changed anymore. However I nevertheless wanted to point this out as it caused us some troubles and was not obvious to discover instantly. 

Christian

**Comment by ghost** [comment]
HI @ChristianPraherKoeppl,

thanks for letting us now! I wasn't even aware of that issue. Since the SDK is already deprecated, we won't fix that. It might be helpful for other customers, though.

Cheers
